# Numpy and Inbuilt Function

In [30]:
import numpy as np

In [31]:
list=[9,8,7,6,5,4]
arr=np.array(list)

In [32]:
arr

array([9, 8, 7, 6, 5, 4])

In [33]:
type(arr)

numpy.ndarray

In [34]:
#Multilisted array
list=[9,8,7,6,5,4]
list1=[3,2,1,0,9,8]
list2=[7,6,5,4,3,2]
arr=np.array([list,list1,list2])

In [35]:
arr

array([[9, 8, 7, 6, 5, 4],
       [3, 2, 1, 0, 9, 8],
       [7, 6, 5, 4, 3, 2]])

In [36]:
arr.shape

(3, 6)

In [37]:
arr.reshape(6,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1],
       [0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [38]:
#Indexing
arr[1:,2:4]

array([[1, 0],
       [5, 4]])

In [39]:
arr=np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr=np.arange(0,17,step=3)

In [46]:
arr

array([ 0,  3,  6,  9, 12, 15])

In [47]:

arr[3:]=100

In [48]:
arr

array([  0,   3,   6, 100, 100, 100])

In [50]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr>3]

array([  6, 100, 100, 100])

In [51]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:

arr1=np.arange(0,10).reshape(2,5)

In [53]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
arr2=np.arange(0,10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [62]:
mylist=[2,3,4,5,6,7,8,9,10,11,12,13,14]

In [63]:
mylist

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [70]:
arr=np.array(mylist)

In [71]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
mylist2=[4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,15,16]

In [73]:
arr1=np.array(mylist2)

In [75]:
(arr)*(arr1)

array([  8,  15,  24,  35,  48,  63,  80,  99, 120, 143, 168, 195, 224])

In [76]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
## random distribution
np.random.rand(3,3)

array([[0.80955401, 0.13524664, 0.89469963],
       [0.83407035, 0.48978033, 0.03831852],
       [0.74879028, 0.58723457, 0.87712099]])

In [78]:
arr_ex=np.random.randn(4,4)

In [79]:
arr_ex

array([[-0.74885171, -1.22422628,  1.567397  ,  2.08831332],
       [-0.0164767 , -1.38832563, -0.77429786,  1.31731969],
       [-0.81615354,  0.47591031,  0.57710631, -1.15191712],
       [ 1.38810301,  1.03693998, -0.79002459, -0.28330326]])

In [80]:
np.random.randint(0,100,8).reshape(4,2)

array([[72,  9],
       [61, 93],
       [ 9, 54],
       [74, 13]])

In [81]:
np.random.random_sample((1,5))

array([[0.66220784, 0.21028071, 0.85499777, 0.5465054 , 0.04792392]])