In [1]:
import numpy as np

In [3]:
arr=np.array([7,8,9])

In [4]:
arr

array([7, 8, 9])

In [7]:
#creating rank 2 array
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [15]:
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print(sliced_arr)
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

[[-1.  0.]
 [ 4.  6.]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [16]:
# Printing elements at specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


# Python program to demonstrate
# basic operations on single array
 

In [17]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

In [18]:
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               

In [19]:
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 

Adding 1 to every element: [[2 3]
 [4 5]]


In [21]:
print(b+6)

[[10  9]
 [ 8  7]]


In [22]:
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)


Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]


In [23]:
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())


Sum of all array elements:  10


In [24]:
print(b.sum())

10


In [25]:
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [26]:
print(a+b)

[[5 5]
 [5 5]]


In [29]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
  

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [36]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
  

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [32]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [37]:
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.98709786 0.67630467]
 [0.73713318 0.50681904]]


In [38]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [39]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [41]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
  
newarr = arr.reshape(2, 2, 3)

In [42]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [51]:
X=np.array([[1,2,3],[9,8,7]])
Y=np.array([[4,5,6],[2,3,4]])
new_arr=np.vstack((X,Y))
new_arr

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6],
       [2, 3, 4]])

In [52]:
new_arr=np.hstack((X,Y))
new_arr


array([[1, 2, 3, 4, 5, 6],
       [9, 8, 7, 2, 3, 4]])

In [54]:
Z=[5,6]
# stacking columns
print("\nColumn stacking:\n", np.column_stack((X, Z)))


Column stacking:
 [[1 2 3 5]
 [9 8 7 6]]


In [55]:
# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((X, Y), 1))


Concatenating to 2nd axis:
 [[1 2 3 4 5 6]
 [9 8 7 2 3 4]]


In [56]:
# Integer datatype
x = np.array([1, 2])  
print(x.dtype)

int32


In [57]:
# Float datatype
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  


Float Datatype: 
float64


In [58]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


In [62]:
arr1=np.array([[7,8],[6,9]],dtype=np.float64)
arr2=np.array([[2,3],[4,6]],dtype=np.int)


array([[2, 3],
       [4, 6]])

In [63]:
arr1

array([[7., 8.],
       [6., 9.]])

In [64]:
arr2

array([[2, 3],
       [4, 6]])

In [67]:
#addition of array
sum=np.add(arr1,arr2)
sum

array([[ 9., 11.],
       [10., 15.]])

In [69]:
print(arr1+arr2)

[[ 9. 11.]
 [10. 15.]]


In [68]:
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
30.0


In [70]:
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 



Square root of Array1 elements: 
[[2.64575131 2.82842712]
 [2.44948974 3.        ]]


In [71]:
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[7. 6.]
 [8. 9.]]


# INDEXING

In [72]:
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)


 A sequential array with a negative step: 
 [10  8  6  4  2]


In [74]:
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
newarr

array([4, 8, 6])

In [77]:
# NumPy array with elements from 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
# Index values can be negative.
arr = x[np.array([1, 3, -4])]
print("\n Elements are : \n",arr)


 Elements are : 
 [2 4 6]


In [79]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
a[-8:17:1] # a[start:stop:step]

array([12, 13, 14, 15, 16])

In [83]:
#The : operator means all elements till the end.
print("\n a[10:]  = ",a[10:])


 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [84]:
a[8:-1]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

# Silicing & Indexing

In [88]:
#A 3-Dimensional array
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])


In [89]:
print("\n Array is:\n ",a)


 Array is:
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [90]:
a[0, 3:5]

array([3, 4])

In [91]:
a[4:, 4:]

array([[28, 29],
       [34, 35]])

In [92]:
a[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [94]:
a[2::2, ::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [96]:
a[0::1,::1]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [97]:
# Python program for indexing using basic slicing with ellipsis
# A 3 dimensional array.
b = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9],[10, 11, 12]]])
 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]

[[ 2  5]
 [ 8 11]]


In [98]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [104]:
# Python program showing advanced and basic indexing
 
a = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
 
print(a[1:2 ,1:3 ])
print(a[1:2 ,[1,2]])

[[4 5]]
[[4 5]]


In [105]:
#boolen array indexing
# You may wish to select numbers greater than 50
import numpy as np
 
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


In [108]:
a = np.array([10, 40, 80, 50, 100])  #You may wish to square the multiples of 40 
print(a[a%40==0]**2)

[1600 6400]


In [107]:
b = np.array([[5, 5],[4, 5],[16, 4]])   # sum of row is a multiple of 10.
sumrow = b.sum(-1)
print(b[sumrow%10==0])

[[ 5  5]
 [16  4]]
